name: C/C++ CI

on: [ push, pull_request ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install Dependencies
      run: sudo apt update && sudo apt install curl libcurl4-openssl-dev libjson-c-dev cmake build-essential autoconf automake libjson-c-dev -y
    - name: Install concord
      run: git clone https://github.com/Cogmasters/concord && cd concord && make && sudo make install && cd ..
    - name: Install json-c
      run: sudo apt install 
    - name: Run autoreconf
      run: autoreconf -i
    - name: Build
      run: ./configure; make; sudo make install; make distcheck