name: C/C++ CI

on: [ push, pull_request ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install Dependencies
      run: sudo apt-get install curl libcurl4-openssl-dev libjson-c-dev
    - name: Install concord
      run: git clone https://github.com/Cogmasters/concord && cd concord && make && sudo make install
    - name: configure
      run: chmod 755 ./configure && ./configure
    - name: make
      run: make
    - name: make check
      run: make check
    - name: make distcheck
      run: make distcheck
